version: '3.8'
services:
  db:
    container_name: db
    image: postgres:15.0-alpine
    ports:
      - 5433:5432
    restart: always
    volumes: 
      - postgres_volume:/var/lib/postgresql/data
    env_file:
      - ./.env
  app:
    container_name: app
    build: .
    restart: always
    ports:
      - "80:80"
    volumes:
      - media_volume:/fastapi_app/upload_files/
    env_file:
      ./.env
    depends_on:
      - db

volumes:
  postgres_volume:
  media_volume: